- name: Run Updates on Windows Servers then wait 7 mins and restart 
  hosts: all

  tasks:
    win_updates:
      category_names:
        - Application
        - CriticalUpdates
        - DefinitionUpdates
        - SecurityUpdates
        - Updates
    reboot: yes
    reboot_timeout: 420
