- hosts: All
  vars:
    win_updates_categories:
      - SecurityUpdates
      - CriticalUpdates
      - UpdateRollups
      - DefinitionUpdates
      - Updates

  tasks:
    # Check for missing updates
    - name: check for missing updates
      win_updates: 
        state: searched
        catagory_names: "{{ win_updates_categories }}"
      register: update_count
      ignore_errors: yes
    
    - name: reboot if required
      win_reboot:
      when: update_count.reboot_required
      ignore_errors: yes
    
    # Install updates    
    - name: install updates
      win_updates:
        catagory_names: "{{ win_updates_categories }}"
        reboot: yes
      register: update_result
